### ISSUE TITLE
 java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by linuxhsj** [tiann/FreeReflection#19]
E/Reflection: reflect bootstrap failed:
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at me.weishu.reflection.Reflection.<clinit>(Reflection.java:32)
        at com.tm.camera.App.attachBaseContext(App.java:43)
        at android.app.Application.attach(Application.java:181)
        at android.app.Instrumentation.newApplication(Instrumentation.java:996)
        at android.app.Instrumentation.newApplication(Instrumentation.java:980)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:558)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4526)
        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
        at android.app.ActivityThread.handleBindApplication(<Xposed>)
        at android.app.ActivityThread.access$1500(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
     Caused by: java.lang.NoSuchMethodException: setHiddenApiExemptions [class [Ljava.lang.String;]
        at java.lang.Class.getMethod(Class.java:664)
        at java.lang.Class.getDeclaredMethod(Class.java:626)
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at me.weishu.reflection.Reflection.<clinit>(Reflection.java:32) 
        at com.tm.camera.App.attachBaseContext(App.java:43)

**Comment by linuxhsj** [comment]
@tiann

**Comment by tiann** [comment]
大兄弟，你就贴个堆栈有什么用？你的告诉我你什么系统，什么场景下出现的。
我看这个堆栈，系统装了 Xposed，9.0以下的系统不需要用这个。
