### ISSUE TITLE
在安卓12 报 W/BootstrapClass: reflect bootstrap failed，对使用有影响吗

### ISSUE THREAD

**Issue by kinpowoo** [tiann/FreeReflection#41]
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at me.weishu.reflection.BootstrapClass.<clinit>(BootstrapClass.java:29)
        at me.weishu.reflection.BootstrapClass.exemptAll(BootstrapClass.java:72)
        at me.weishu.reflection.Reflection.unseal(Reflection.java:35)
        at com.jhkj.neabot.app.MainApplication.initApp(MainApplication.java:72)
        at com.jhkj.neabot.app.MainApplication.onCreate(MainApplication.java:65)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6728)
        at android.app.ActivityThread.access$1500(ActivityThread.java:247)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2057)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.NoSuchMethodException: dalvik.system.VMRuntime.setHiddenApiExemptions [class [Ljava.lang.String;]
        at java.lang.Class.getMethod(Class.java:2103)
        at java.lang.Class.getDeclaredMethod(Class.java:2081)

**Comment by so-lli** [comment]
set targetSdkVersion = 29

**Comment by tiann** [comment]
没影响
