### ISSUE TITLE
尝试了小米12失败了

### ISSUE THREAD

**Issue by a834286983** [tiann/FreeReflection#47]
报错打印
2022-07-15 17:31:39.016 8175-8175/? W/BootstrapClass: reflect bootstrap failed:
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at me.weishu.reflection.BootstrapClass.<clinit>(BootstrapClass.java:29)
        at me.weishu.reflection.BootstrapClass.exemptAll(Unknown Source:0)
        at me.weishu.reflection.Reflection.unseal(Reflection.java:35)
        at org.cocos2dx.lua.AppActivity.attachBaseContext(AppActivity.java:212)
        at android.app.Activity.attach(Activity.java:8115)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3702)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3929)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2282)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8250)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
     Caused by: java.lang.NoSuchMethodException: dalvik.system.VMRuntime.setHiddenApiExemptions [class [Ljava.lang.String;]
        at java.lang.Class.getMethod(Class.java:2103)
        at java.lang.Class.getDeclaredMethod(Class.java:2081)
        at java.lang.reflect.Method.invoke(Native Method) 
        at me.weishu.reflection.BootstrapClass.<clinit>(BootstrapClass.java:29) 
        at me.weishu.reflection.BootstrapClass.exemptAll(Unknown Source:0) 
        at me.weishu.reflection.Reflection.unseal(Reflection.java:35) 
        at org.cocos2dx.lua.AppActivity.attachBaseContext(AppActivity.java:212) 
        at android.app.Activity.attach(Activity.java:8115) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3702) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3929) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2282) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:210) 
        at android.os.Looper.loop(Looper.java:299) 
        at android.app.ActivityThread.main(ActivityThread.java:8250) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045) 

SDK等级
       # Android SDK version that will be used as the compile project
      PROP_COMPILE_SDK_VERSION=31
      
      # Android SDK version that will be used as the earliest version of android this application can run on
      PROP_MIN_SDK_VERSION=21
      
      # Android SDK version that will be used as the latest version of android this application has been tested on
      PROP_TARGET_SDK_VERSION=30

**Comment by qzhuorui** [comment]
+1

**Comment by guozhongrui000** [comment]
+1

**Comment by igottime** [comment]
我也是，虽然报错了，但是限制还是解除了。

**Comment by tiann** [comment]
报错不用管。
