### ISSUE TITLE
Writable dex file is not allowed

### ISSUE THREAD

**Issue by Mygod** [tiann/FreeReflection#56]
It fails to work when targeting API 34 due to this: https://developer.android.com/about/versions/14/behavior-changes-14#safer-dynamic-code-loading

**Comment by hushenghao** [comment]
It looks like this is an issue that has to be fixed, and it can be replicated on Android U preview.
```logcat
09:26:46.979 de.android_eggs          E  Attempt to load writable dex file: /data/user/0/com.dede.android_eggs/code_cache/1687051606978.dex
09:26:46.980 Compatibil...geReporter  D  Compat change id reported: 218865702; UID 10168; state: ENABLED
09:26:46.981 System.err               W  java.lang.SecurityException: Writable dex file '/data/user/0/com.dede.android_eggs/code_cache/1687051606978.dex' is not allowed.
09:26:46.981 System.err               W  	at dalvik.system.DexFile.openDexFileNative(Native Method)
09:26:46.982 System.err               W  	at dalvik.system.DexFile.openDexFile(DexFile.java:406)
09:26:46.982 System.err               W  	at dalvik.system.DexFile.<init>(DexFile.java:128)
09:26:46.982 System.err               W  	at dalvik.system.DexFile.<init>(DexFile.java:113)
09:26:46.982 System.err               W  	at dalvik.system.DexFile.<init>(DexFile.java:87)
09:26:46.983 System.err               W  	at me.weishu.reflection.Reflection.unsealByDexFile(Reflection.java:58)
09:26:46.983 System.err               W  	at me.weishu.reflection.Reflection.unseal(Reflection.java:38)
09:26:46.983 System.err               W  	at com.dede.android_eggs.startup.ReflectionInitializer.create(ReflectionInitializer.kt:11)
09:26:46.984 System.err               W  	at com.dede.android_eggs.startup.ReflectionInitializer.create(ReflectionInitializer.kt:8)
09:26:46.985 System.err               W  	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
09:26:46.985 System.err               W  	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:173)
09:26:46.985 System.err               W  	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238)
09:26:46.985 System.err               W  	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
09:26:46.986 System.err               W  	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
09:26:46.986 System.err               W  	at android.content.ContentProvider.attachInfo(ContentProvider.java:2510)
09:26:46.986 System.err               W  	at android.content.ContentProvider.attachInfo(ContentProvider.java:2480)
09:26:46.987 System.err               W  	at android.app.ActivityThread.installProvider(ActivityThread.java:7716)
09:26:46.987 System.err               W  	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7227)
09:26:46.987 System.err               W  	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6946)
09:26:46.987 System.err               W  	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
09:26:46.988 System.err               W  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2222)
09:26:46.988 System.err               W  	at android.os.Handler.dispatchMessage(Handler.java:106)
09:26:46.989 System.err               W  	at android.os.Looper.loopOnce(Looper.java:205)
09:26:46.989 System.err               W  	at android.os.Looper.loop(Looper.java:294)
09:26:46.989 System.err               W  	at android.app.ActivityThread.main(ActivityThread.java:8128)
09:26:46.989 System.err               W  	at java.lang.reflect.Method.invoke(Native Method)
09:26:46.989 System.err               W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
09:26:46.990 System.err               W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
```

**Comment by amanyadavpims** [comment]
Just uninstall the existing app from mobile or emulator will work.
